### ISSUE TITLE
The 'either' statement is incorrectly parsed via cfg

### ISSUE THREAD

**Issue by karloyz** [itsallcode/holiday-calculator#62]
I am currently testing this holiday library, and I configured US Independence Day like this:

```
holiday either  JUL  4 or if SUN then fixed JUL 5         Independence Day
holiday either  JUL  4 or if Sat then fixed JUL 3         Independence Day
```

However, the result for Year 2026 Jul 4 is mis-parsed as Jul 5. (Jul 3 is expected).

I debugged into the code, and found this place has an issue:

HolidayMatcher.java
```
	public ConditionBuilder createConditionBuilder(Matcher matcher) {
		return new ConditionBuilder()
				.withDaysOfWeek(daysOfWeek(matcher.group(Patterns.PIVOT_DAYS_OF_WEEK_GROUP)))
				.withPivotDate(monthDay(
						matcher.group(Patterns.**MONTH_GROUP_2**), matcher.group(Patterns.**DAY_GROUP_2**)));
	}
```

In this code, the matcher should use Patterns.**MONTH_GROUP** and Patterns.**DAY_GROUP** instread.

Kindly check or if I can fix with a pull request?

Thanks

**Comment by ckunki** [comment]
Hello @karloyz many thanks for your issue report and special thanks for being that precise. 
I will fix the issue during the weekend and provide an updated version.

**Comment by karloyz** [comment]
@ckunki Thank you for quick response and fix! It's a wonderful library that helped a lot!

**Comment by kaklakariada** [comment]
@karloyz Great that you like our project :-)
We just released https://github.com/itsallcode/holiday-calculator/releases/tag/0.2.1 with the fix.
It should be available on Maven Central soon: https://repo1.maven.org/maven2/org/itsallcode/holiday-calculator/0.2.1/

**Comment by ckunki** [comment]
Special credits to @kaklakariada for fixing the sonar setup and doing the release!
